services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: rag-api
    volumes:
      - ./backend:/app
      - ./data/uploaded_files:/app/data/uploaded_files
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    depends_on:
      - qdrant
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  qdrant:
    image: qdrant/qdrant:latest
    container_name: vector-db
    ports:
     - "${QDRANT_API_PORT}:${QDRANT_API_PORT}"
     - "${QDRANT_GRPC_PORT}:${QDRANT_GRPC_PORT}"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
    driver: local
